# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

################################################################################
# Use Python image for base image for all stages.
FROM docker.io/digitop/facefusion:v0-2-11-1 as base

# Set working directory for all build stages.
WORKDIR /usr/src/python-app

COPY . .

RUN . /venv/bin/activate && \
    python install.py --onnxruntime default --skip-conda && \
    pip install -r requirements.txt

RUN . /venv/bin/activate && \
    python facefusion.py headless-run --face-mask-blur 0.1 --face-enhancer-model gfpgan_1.4 --output-image-quality 100 --face-selector-mode reference --temp-frame-format png -s "./tests/images/elon-1.jpg" -t "./tests/images/mark.jpg" -o "./tests/images/output.png"

EXPOSE 3000

# Use exec form and activate venv properly
CMD ["/bin/bash", "-c", ". /venv/bin/activate && python facefusion.py api"]