# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

################################################################################
# Use Python image for base image for all stages.
FROM python:3.12 as base

# Set working directory for all build stages.
WORKDIR /usr/src/python-app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    curl \
    gcc \
    g++ \
    git \
    && rm -rf /var/lib/apt/lists/*

ENV GRADIO_SERVER_NAME=0.0.0.0

# RUN git clone https://github.com/digitopvn/facefusion.git --branch dev/tam --single-branch --depth 1 facefusion

# Create a virtual environment
RUN python3 -m venv /venv

# Activate the virtual environment before installing packages
RUN . /venv/bin/activate && pip install inquirer insightface opennsfw2 tensorflow && \
    pip install basicsr facexlib && \
    pip install realesrgan

COPY . .

RUN . /venv/bin/activate && \
    python install.py --onnxruntime default --skip-conda && \
    pip install -r requirements.txt

RUN . /venv/bin/activate && \
    python facefusion.py headless-run --face-mask-blur 0.1 --face-enhancer-model gfpgan_1.4 --output-image-quality 100 --face-selector-mode reference --temp-frame-format png -s "./tests/images/elon-1.jpg" -t "./tests/images/mark.jpg" -o "./tests/images/output.png"

EXPOSE 3000

# Use exec form and activate venv properly
CMD ["/bin/bash", "-c", ". /venv/bin/activate && python facefusion.py api"]